FROM agrigorev/model-2025-hairstyle:v1

WORKDIR /var/task

RUN pip install --no-cache-dir \
        numpy \
        pillow \
        onnxruntime \
        torch \
        torchvision

COPY lambda_function.py ./
